services:
  app:
    container_name: anilyzer-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      DATABASE_URL: /app/data/series.sqlite
      LOCAL_TS_FILE: /app/data/series.timestamp.local
      PORT: 3000
    healthcheck:
      test: 'wget --no-verbose --spider --timeout=1 http://localhost:3000/health || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped